# pip install -r requirements.txt
# mkdocs serve


extra:
  fladle:
    current_release: '0.11.0'
    next_release: '0.11.1'
    flank_version: '20.08.4'

site_name: Fladle
site_url: https://runningcode.github.io/fladle/
repo_name: Fladle
repo_url: https://github.com/runningcode/fladle/
site_description: The Gradle Plugin for Firebase Test Lab and Flank
site_author: Nelson Osacky

nav:
  - Home: index.md
  - Quick Start: quick-start.md
  - Configuration: configuration.md
  - Changelog: changelog.md
  - Results: results.md
  - Multi Module Testing: multi-module-testing.md
  - FAQ: faq.md
  - Testing Snapshots: snapshots.md
  - Releasing: releasing.md

theme:
  name: 'material'

markdown_extensions:
  - codehilite
  - admonition
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.tabbed:

plugins:
  - search
  - markdownextradata: {}
